### ISSUE TITLE
Fails with fish shell

### ISSUE THREAD

**Issue by cschneid** [pechorin/any-jump.vim#50]
I use fish shell normally, and launch nvim through it. When calling :AnyJump, I get:

```
Error detected while processing function <SNR>83_Jump[30]..search#SearchDefinitions[28]..<SNR>246
_RunRgDefinitionSearch[8]..<SNR>246_ParseRgResults:
line    7:
E474: Expected false: fish: $) is not a valid variable in fish.
E474: Failed to parse fish: $) is not a valid variable in fish.
Press ENTER or type command to continue
```

**Comment by pechorin** [comment]
Okay, thanks for report, will check it out.

**Comment by michalvalasek** [comment]
I'm having the same problem.

It looks like the problem might be on Fish's side since this wasn't happening last week and I haven't updated my any-jump clone in the meantime.

**Comment by cschneid** [comment]
data point: I switched to bash, launched and still got the same error. So reproducing may require you to change your default shell (globally or vim? unsure) to fish.

**Comment by pechorin** [comment]
i think you should try `:set shell=/bin/bash` but this is just a temp fix, sorry

**Comment by pechorin** [comment]
Fixed in https://github.com/pechorin/any-jump.vim/commit/e5ecc73fb00a50097250106118a4b3414809497c, please report if it helps or not.

**Comment by michalvalasek** [comment]
So I updated any-jump locally and tried it again.
- When I first `cd` into a project folder, then `vim .`, then go to a file via ctrl-P: **any-jump works**
- When I open the project dir directly like `vim ~/code/projectname` and then do the same: I'm **still getting the error**.

**Comment by pechorin** [comment]
@cschneid is it fixed for you?

**Comment by cschneid** [comment]
A quick check appears to be working. I haven't comprehensively tested, but a few lookups and jumps worked as expected.

Thank you!

**Comment by pechorin** [comment]
Thanks, i will close it. Please report if any issue with fish shell, it should work fine.
